### ISSUE TITLE
Clean logging error from tests

### ISSUE THREAD

**Issue by tebeka** [mlrun/mlrun#101]
At the end of the tests we see the following output. It doesn't fail the test but it's annoying.
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
  File "/usr/local/lib/python3.6/site-packages/_pytest/capture.py", line 427, in write
    self.buffer.write(obj)
ValueError: I/O operation on closed file
Call stack:
  File "/usr/local/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/mlrun/mlrun/db/periodic.py", line 35, in _schedule
    logger.info('running periodic task')
Message: 'running periodic task'
Arguments: ()
```

**Comment by tebeka** [comment]
Seems like `test_dask.py` is the problem

**Comment by tebeka** [comment]
@yaronha When install from `requirements.txt` containg the following
```
kfp==0.1.38
kubernetes==10.0.1
```

I see an error
```
ERROR: kfp 0.1.38 has requirement kubernetes<=9.0.0,>=8.0.0, but you'll have kubernetes 10.0.1 which is incompatible.
```
But the installation process finished without an error and:
```
Python 3.8.1 (default, Dec 21 2019, 20:57:38) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kfp
>>> kfp.__version__
'0.1.38'
>>> import kubernetes
>>> kubernetes.__version__
'10.0.1'
>>> 
```

**Comment by tebeka** [comment]
Seems it's related to pytest capturing stdout, see [here](https://github.com/pytest-dev/pytest/issues/5577)
