### ISSUE TITLE
Switch to using sqldb

### ISSUE THREAD

**Issue by tebeka** [mlrun/mlrun#140]

**Comment by tebeka** [comment]
@yaronha said:
```
[2020-01-30 19:07:56,884] ERROR in app: Exception on /api/run/default/122c53b8bef14cf2a5f5a1dee348df65 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mlrun/mlrun/db/httpd.py", line 109, in wrapper
    return fn(*args, **kw)
  File "/mlrun/mlrun/db/httpd.py", line 515, in store_run
    _db.store_run(data, uid, project, iter=iter)
  File "/mlrun/mlrun/db/sqldb.py", line 160, in store_run
    run = self._get_run(uid, project, iter)
  File "/mlrun/mlrun/db/sqldb.py", line 359, in _get_run
    Run, uid=uid, project=project, iteration=iteration).one_or_none()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3325, in one_or_none
    "Multiple rows were found for one_or_none()"
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one_or_none()
10.233.64.53 - - [30/Jan/2020 19:07:56] "POST /api/run/default/122c53b8bef14cf2a5f5a1dee348df65?iter=0 HTTP/1.1" 500 -
1  P/1.1" 200 -
[2020-01-30 19:07:57,909] ERROR in app: Exception on /api/run/default/122c53b8bef14cf2a5f5a1dee348df65 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mlrun/mlrun/db/httpd.py", line 109, in wrapper
    return fn(*args, **kw)
  File "/mlrun/mlrun/db/httpd.py", line 540, in read_run
    data = _db.read_run(uid, project, iter=iter)
  File "/mlrun/mlrun/db/sqldb.py", line 198, in read_run
    run = self._get_run(uid, project, iter)
  File "/mlrun/mlrun/db/sqldb.py", line 359, in _get_run
    Run, uid=uid, project=project, iteration=iteration).one_or_none()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3325, in one_or_none
    "Multiple rows were found for one_or_none()"
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one_or_none()
10.233.64.52 - - [30/Jan/2020 19:07:57] "GET /api/run/default/122c53b8bef14cf2a5f5a1dee348df65?iter=0 HTTP/1.1
```
