### ISSUE TITLE
Using FeatureStore without V3IO config

### ISSUE THREAD

**Issue by cyliu0204** [mlrun/mlrun#1611]
Can I use featurestore without V3IO_API config? Is there a way to use S3 instead?
Got the following error when I try to run the fraud prevention-feature-store demo

> 2022-01-05 09:14:11,749 [error] Pushing error to error stream: Endpoints must be passed to context or specified in V3IO_API
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/storey/flow.py", line 139, in _do_and_recover
    return await self._do(event)
  File "/opt/conda/lib/python3.8/site-packages/storey/flow.py", line 770, in _do
    await self._emit_batch(key)
  File "/opt/conda/lib/python3.8/site-packages/storey/flow.py", line 798, in _emit_batch
    await self._emit(batch_to_emit, batch_key, batch_time, last_event_time)
  File "/opt/conda/lib/python3.8/site-packages/storey/targets.py", line 362, in _emit
    await self._blocking_io_loop_future
  File "/opt/conda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.8/site-packages/storey/targets.py", line 345, in _blocking_io_loop
    raise ex
  File "/opt/conda/lib/python3.8/site-packages/storey/targets.py", line 320, in _blocking_io_loop
    fs, file_path = url_to_file_system(self._path, self._storage_options)
  File "/opt/conda/lib/python3.8/site-packages/storey/utils.py", line 114, in url_to_file_system
    return fsspec.filesystem(schema, **storage_options), url
  File "/opt/conda/lib/python3.8/site-packages/fsspec/registry.py", line 244, in filesystem
    return cls(**storage_options)
  File "/opt/conda/lib/python3.8/site-packages/fsspec/spec.py", line 69, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/v3iofs/fs.py", line 50, in __init__
    self._client = _new_client(v3io_api, v3io_access_key)
  File "/opt/conda/lib/python3.8/site-packages/v3iofs/fs.py", line 308, in _new_client
    return Client(
  File "/opt/conda/lib/python3.8/site-packages/v3io/dataplane/client.py", line 69, in __init__
    self._transport = transport_cls.Transport(self._logger,
  File "/opt/conda/lib/python3.8/site-packages/v3io/dataplane/transport/httpclient.py", line 14, in __init__
    super(Transport, self).__init__(logger, endpoint, max_connections, timeout, verbosity)
  File "/opt/conda/lib/python3.8/site-packages/v3io/dataplane/transport/abstract.py", line 11, in __init__
    self._endpoint = self._get_endpoint(endpoint)
  File "/opt/conda/lib/python3.8/site-packages/v3io/dataplane/transport/abstract.py", line 66, in _get_endpoint
    raise RuntimeError('Endpoints must be passed to context or specified in V3IO_API')
RuntimeError: Endpoints must be passed to context or specified in V3IO_API

**Comment by cyliu0204** [comment]
resolve it by setting the following env
os.environ["MLRUN_FEATURE_STORE__DATA_PREFIXES__DEFAULT"]="s3://xxx/{project}/FeatureStore/{name}/{kind}"
os.environ["MLRUN_FEATURE_STORE__DATA_PREFIXES__NOSQL"]="s3://xxx/{project}/FeatureStore/{name}/{kind}"
