### ISSUE TITLE
db error in new project

### ISSUE THREAD

**Issue by tebeka** [mlrun/mlrun#177]
@yaronha said:
```
10.233.64.60 - - [28/Feb/2020 16:17:27] "POST /api/run/image-classification/c613319190f54209b867986753fd0c6d?iter=0 HTTP/1.1" 200 -
[mlrun] 2020-02-28 16:17:27,736 {'metadata': {'name': 'train', 'uid': 'c613319190f54209b867986753fd0c6d', 'iteration': 0, 'project': 'image-classification', 'labels': {'workflow': 'bce78720-09bd-400f-a5cf-989a2bfa172a', 'kind': 'mpijob', 'owner': 'root', 'mlrun/job': 'train-a4696566', 'host': 'train-a4696566-worker-1'}, 'annotations': {}}, 'spec': {'function': 'image-classification/horovod-trainer:24d41dd3350632dc8920b63d1f8d2f107283a68d', 'log_level': 'info', 'parameters': {'epochs': 1, 'checkpoints_dir': '/User/mlrun/examples/checkpoints', 'model_path': '/User/mlrun/examples/models/cats_n_dogs.h5', 'data_path': '/User/mlrun/examples/images/cats_n_dogs', 'use_gpu': True, 'image_width': 128}, 'outputs': ['model'], 'output_path': 'v3io:///users/admin/mlrun/kfp/bce78720-09bd-400f-a5cf-989a2bfa172a/', 'inputs': {'categories_map': '/User/mlrun/examples/images/categories_map.json', 'file_categories': '/User/mlrun/examples/images/file_categories_df.csv'}, 'data_stores': []}, 'status': {'state': 'running', 'results': {}, 'start_time': '2020-02-28 16:17:27.678750', 'last_update': '2020-02-28 16:17:27.678756', 'artifacts': []}}
[mlrun] 2020-02-28 16:17:27,740 {'metadata': {'name': 'train', 'uid': 'c613319190f54209b867986753fd0c6d', 'iteration': 0, 'project': 'image-classification', 'labels': {'workflow': 'bce78720-09bd-400f-a5cf-989a2bfa172a', 'kind': 'mpijob', 'owner': 'root', 'mlrun/job': 'train-a4696566', 'host': 'train-a4696566-worker-2'}, 'annotations': {}}, 'spec': {'function': 'image-classification/horovod-trainer:24d41dd3350632dc8920b63d1f8d2f107283a68d', 'log_level': 'info', 'parameters': {'epochs': 1, 'checkpoints_dir': '/User/mlrun/examples/checkpoints', 'model_path': '/User/mlrun/examples/models/cats_n_dogs.h5', 'data_path': '/User/mlrun/examples/images/cats_n_dogs', 'use_gpu': True}, 'outputs': ['model'], 'output_path': 'v3io:///users/admin/mlrun/kfp/bce78720-09bd-400f-a5cf-989a2bfa172a/', 'inputs': {'categories_map': '/User/mlrun/examples/images/categories_map.json', 'file_categories': '/User/mlrun/examples/images/file_categories_df.csv'}, 'data_stores': []}, 'status': {'state': 'running', 'results': {}, 'start_time': '2020-02-28 16:17:27.705642', 'last_update': '2020-02-28 16:17:27.705646', 'artifacts': []}}
[2020-02-28 16:17:27,741] ERROR in app: Exception on /api/run/image-classification/c613319190f54209b867986753fd0c6d [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mlrun/mlrun/db/httpd.py", line 129, in wrapper
    return fn(*args, **kw)
  File "/mlrun/mlrun/db/httpd.py", line 585, in store_run
    _db.store_run(data, uid, project, iter=iter)
  File "/mlrun/mlrun/db/sqldb.py", line 160, in store_run
    run = self._get_run(uid, project, iter)
  File "/mlrun/mlrun/db/sqldb.py", line 373, in _get_run
    Run, uid=uid, project=project, iteration=iteration).one_or_none()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3316, in one_or_none
    ret = list(self)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3389, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3411, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3426, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3404, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1133, in connection
    execution_options=execution_options,
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1139, in _connection_for_bind
    engine, execution_options
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 408, in _connection_for_bind
    self._assert_active()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 282, in _assert_active
    "This session is in 'prepared' state; no further "
sqlalchemy.exc.InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.
```

**Comment by tebeka** [comment]
Tried the attached, couldn't reproduce.

[test_httpd_stress.py.gz](https://github.com/mlrun/mlrun/files/4271964/test_httpd_stress.py.gz)

**Comment by tebeka** [comment]
@yaronha Changed all threads to run on single object - still no error.
[test_httpd_stress1.py.gz](https://github.com/mlrun/mlrun/files/4282255/test_httpd_stress1.py.gz)

**Comment by Hedingber** [comment]
Should be resolved from the migration from flask to FastAPI, closing
