### ISSUE TITLE
Error in build function

### ISSUE THREAD

**Issue by tebeka** [mlrun/mlrun#218]
@yaronha said:
```
10.200.0.50 - - [15/Mar/2020 21:11:18] "POST /api/build/function HTTP/1.1" 308 -
[mlrun] 2020-03-15 21:11:18,909 build_function:
{'function': {'kind': 'job', 'metadata': {'name': 'my-trainer', 'tag': '', 'project': '', 'categories': []}, 'spec': {'command': '', 'args': [], 'volumes': [{'flexVolume': {'driver': 'v3io/fuse', 'options': {'accessKey': 'b67da110-f17f-48ce-a70a-851940333036', 'container': 'users', 'subPath': '/admin'}}, 'name': 'v3io'}], 'volume_mounts': [{'mountPath': '/User', 'name': 'v3io'}], 'env': [{'name': 'V3IO_API', 'value': 'v3io-webapi.default-tenant.svc:8081'}, {'name': 'V3IO_USERNAME', 'value': 'admin'}, {'name': 'V3IO_ACCESS_KEY', 'value': 'b67da110-f17f-48ce-a70a-851940333036'}], 'description': '', 'build': {'functionSourceCode': 'IyBHZW5lcmF0ZWQgYnkgbnVjbGlvLmV4cG9ydC5OdWNsaW9FeHBvcnRlciBvbiAyMDIwLTAzLTE1IDIxOjEwCgpmcm9tIG9zIGltcG9ydCBlbnZpcm9uCmVudmlyb25bJ01MUlVOX0RCUEFUSCddID0gZW52aXJvbi5nZXQoJ01MUlVOX0RCUEFUSCcsICdodHRwOi8vbWxydW4tYXBpOjgwODAnKQoKZnJvbSBtbHJ1bi5leGVjdXRpb24gaW1wb3J0IE1MQ2xpZW50Q3R4CmZyb20gbWxydW4uZGF0YXN0b3JlIGltcG9ydCBEYXRhSXRlbQoKaW1wb3J0IHRpbWUKCmRlZiB0cmFpbmluZygKICAgIGNvbnRleHQ6IE1MQ2xpZW50Q3R4LAogICAgcDE6IGludCA9IDEsCiAgICBwMjogaW50ID0gMgopIC0+IE5vbmU6CiAgICAiIiJUcmFpbiBhIG1vZGVsLgoKICAgIDpwYXJhbSBjb250ZXh0OiBUaGUgcnVudGltZSBjb250ZXh0IG9iamVjdC4KICAgIDpwYXJhbSBwMTogQSBtb2RlbCBwYXJhbWV0ZXIuCiAgICA6cGFyYW0gcDI6IEFub3RoZXIgbW9kZWwgcGFyYW1ldGVyLgogICAgIiIiCiAgICBwcmludChmJ1J1bjoge2NvbnRleHQubmFtZX0gKHVpZD17Y29udGV4dC51aWR9KScpCiAgICBwcmludChmJ1BhcmFtczogcDE9e3AxfSwgcDI9e3AyfScpCiAgICBjb250ZXh0LmxvZ2dlci5pbmZvKCdzdGFydGVkIHRyYWluaW5nJykKICAgIAogICAgCiAgICBjb250ZXh0LmxvZ19yZXN1bHQoJ2FjY3VyYWN5JywgcDEgKiAyKQogICAgY29udGV4dC5sb2dfcmVzdWx0KCdsb3NzJywgcDEgKiAzKQogICAgCiAgICBjb250ZXh0LnNldF9sYWJlbCgnY2F0ZWdvcnknLCAndGVzdHMnKQogICAgCiAgICBjb250ZXh0LmxvZ19hcnRpZmFjdCgnbW9kZWwnLCAKICAgICAgICAgICAgICAgICAgICAgICAgICBib2R5PWInYWJjIGlzIDEyMycsIAogICAgICAgICAgICAgICAgICAgICAgICAgIGxvY2FsX3BhdGg9J21vZGVsLnR4dCcsIAogICAgICAgICAgICAgICAgICAgICAgICAgIGxhYmVscz17J2ZyYW1ld29yayc6ICd0ZmtlcmFzJ30pCgpkZWYgdmFsaWRhdGlvbigKICAgIGNvbnRleHQ6IE1MQ2xpZW50Q3R4LAogICAgbW9kZWw6IERhdGFJdGVtCikgLT4gTm9uZToKICAgICIiIk1vZGVsIHZhbGlkYXRpb24uCiAgICAKICAgIER1bW15IHZhbGlkYXRpb24gZnVuY3Rpb24uCiAgICAKICAgIDpwYXJhbSBjb250ZXh0OiBUaGUgcnVudGltZSBjb250ZXh0IG9iamVjdC4KICAgIDpwYXJhbSBtb2RlbDogVGhlIGV4dGltYXRlZCBtb2RlbCBvYmplY3QuCiAgICAiIiIKICAgIHByaW50KGYnUnVuOiB7Y29udGV4dC5uYW1lfSAodWlkPXtjb250ZXh0LnVpZH0pJykKICAgIHByaW50KGYnZmlsZSAtIHttb2RlbC51cmx9Olxue21vZGVsLmdldCgpfVxuJykKICAgIGNvbnRleHQubG9nZ2VyLmluZm8oJ3N0YXJ0ZWQgdmFsaWRhdGlvbicpICAgIAogICAgY29udGV4dC5sb2dfYXJ0aWZhY3QoJ3ZhbGlkYXRpb24nLCAKICAgICAgICAgICAgICAgICAgICAgICAgIGJvZHk9Yic8Yj4gdmFsaWRhdGVkIDwvYj4nLCAKICAgICAgICAgICAgICAgICAgICAgICAgIGZvcm1hdD0naHRtbCcpCgo=', 'image': '.mlrun/func-default-my-trainer-latest', 'base_image': 'mlrun/mlrun', 'commands': ['pip install pandas'], 'code_origin': 'https://github.com/mlrun/mlrun.git#5170e95e2c3495b9606322874913767559d9045f:my-trainer.ipynb'}}, 'status': {'state': ''}}, 'with_mlrun': 'yes'}
[mlrun] 2020-03-15 21:11:18,912 saving function: my-trainer, tag: latest
[mlrun] 2020-03-15 21:11:18,918 building image (.mlrun/func-default-my-trainer-latest)
FROM mlrun/mlrun:0.4.6
RUN pip install pandas
RUN pip install mlrun

[mlrun] 2020-03-15 21:11:18,919 using in-cluster config.
[mlrun] 2020-03-15 21:11:18,935 Pod mlrun-build-my-trainer-tkh7f created
[mlrun] 2020-03-15 21:11:18,935 started build, to watch build logs use "mlrun watch mlrun-build-my-trainer-tkh7f default-tenant"
[mlrun] 2020-03-15 21:11:18,937 saving function: my-trainer, tag: latest
[mlrun] 2020-03-15 21:11:18,955 Fn:
 kind: job
metadata:
  name: my-trainer
  tag: latest
  hash: d9f622ddabcb1f61737d77505352894749306801
  project: ''
  categories: []
spec:
  command: ''
  args: []
  image: ''
  volumes:
  - flexVolume:
      driver: v3io/fuse
      options:
        accessKey: b67da110-f17f-48ce-a70a-851940333036
        container: users
        subPath: /admin
    name: v3io
  volume_mounts:
  - mountPath: /User
    name: v3io
  env:
  - name: V3IO_API
    value: v3io-webapi.default-tenant.svc:8081
  - name: V3IO_USERNAME
    value: admin
  - name: V3IO_ACCESS_KEY
    value: b67da110-f17f-48ce-a70a-851940333036
  description: ''
  build:
    functionSourceCode: IyBHZW5lcmF0ZWQgYnkgbnVjbGlvLmV4cG9ydC5OdWNsaW9FeHBvcnRlciBvbiAyMDIwLTAzLTE1IDIxOjEwCgpmcm9tIG9zIGltcG9ydCBlbnZpcm9uCmVudmlyb25bJ01MUlVOX0RCUEFUSCddID0gZW52aXJvbi5nZXQoJ01MUlVOX0RCUEFUSCcsICdodHRwOi8vbWxydW4tYXBpOjgwODAnKQoKZnJvbSBtbHJ1bi5leGVjdXRpb24gaW1wb3J0IE1MQ2xpZW50Q3R4CmZyb20gbWxydW4uZGF0YXN0b3JlIGltcG9ydCBEYXRhSXRlbQoKaW1wb3J0IHRpbWUKCmRlZiB0cmFpbmluZygKICAgIGNvbnRleHQ6IE1MQ2xpZW50Q3R4LAogICAgcDE6IGludCA9IDEsCiAgICBwMjogaW50ID0gMgopIC0+IE5vbmU6CiAgICAiIiJUcmFpbiBhIG1vZGVsLgoKICAgIDpwYXJhbSBjb250ZXh0OiBUaGUgcnVudGltZSBjb250ZXh0IG9iamVjdC4KICAgIDpwYXJhbSBwMTogQSBtb2RlbCBwYXJhbWV0ZXIuCiAgICA6cGFyYW0gcDI6IEFub3RoZXIgbW9kZWwgcGFyYW1ldGVyLgogICAgIiIiCiAgICBwcmludChmJ1J1bjoge2NvbnRleHQubmFtZX0gKHVpZD17Y29udGV4dC51aWR9KScpCiAgICBwcmludChmJ1BhcmFtczogcDE9e3AxfSwgcDI9e3AyfScpCiAgICBjb250ZXh0LmxvZ2dlci5pbmZvKCdzdGFydGVkIHRyYWluaW5nJykKICAgIAogICAgCiAgICBjb250ZXh0LmxvZ19yZXN1bHQoJ2FjY3VyYWN5JywgcDEgKiAyKQogICAgY29udGV4dC5sb2dfcmVzdWx0KCdsb3NzJywgcDEgKiAzKQogICAgCiAgICBjb250ZXh0LnNldF9sYWJlbCgnY2F0ZWdvcnknLCAndGVzdHMnKQogICAgCiAgICBjb250ZXh0LmxvZ19hcnRpZmFjdCgnbW9kZWwnLCAKICAgICAgICAgICAgICAgICAgICAgICAgICBib2R5PWInYWJjIGlzIDEyMycsIAogICAgICAgICAgICAgICAgICAgICAgICAgIGxvY2FsX3BhdGg9J21vZGVsLnR4dCcsIAogICAgICAgICAgICAgICAgICAgICAgICAgIGxhYmVscz17J2ZyYW1ld29yayc6ICd0ZmtlcmFzJ30pCgpkZWYgdmFsaWRhdGlvbigKICAgIGNvbnRleHQ6IE1MQ2xpZW50Q3R4LAogICAgbW9kZWw6IERhdGFJdGVtCikgLT4gTm9uZToKICAgICIiIk1vZGVsIHZhbGlkYXRpb24uCiAgICAKICAgIER1bW15IHZhbGlkYXRpb24gZnVuY3Rpb24uCiAgICAKICAgIDpwYXJhbSBjb250ZXh0OiBUaGUgcnVudGltZSBjb250ZXh0IG9iamVjdC4KICAgIDpwYXJhbSBtb2RlbDogVGhlIGV4dGltYXRlZCBtb2RlbCBvYmplY3QuCiAgICAiIiIKICAgIHByaW50KGYnUnVuOiB7Y29udGV4dC5uYW1lfSAodWlkPXtjb250ZXh0LnVpZH0pJykKICAgIHByaW50KGYnZmlsZSAtIHttb2RlbC51cmx9Olxue21vZGVsLmdldCgpfVxuJykKICAgIGNvbnRleHQubG9nZ2VyLmluZm8oJ3N0YXJ0ZWQgdmFsaWRhdGlvbicpICAgIAogICAgY29udGV4dC5sb2dfYXJ0aWZhY3QoJ3ZhbGlkYXRpb24nLCAKICAgICAgICAgICAgICAgICAgICAgICAgIGJvZHk9Yic8Yj4gdmFsaWRhdGVkIDwvYj4nLCAKICAgICAgICAgICAgICAgICAgICAgICAgIGZvcm1hdD0naHRtbCcpCgo=
    image: .mlrun/func-default-my-trainer-latest
    base_image: mlrun/mlrun
    commands:
    - pip install pandas
    - pip install mlrun
    code_origin: https://github.com/mlrun/mlrun.git#5170e95e2c3495b9606322874913767559d9045f:my-trainer.ipynb
status:
  state: build
  build_pod: mlrun-build-my-trainer-tkh7f

10.200.0.50 - - [15/Mar/2020 21:11:18] "POST /api/build/function/ HTTP/1.1" 200 -
10.200.0.50 - - [15/Mar/2020 21:11:18] "GET /api/build/status?name=my-trainer&project=&tag=&logs=yes&offset=0 HTTP/1.1" 308 -
[mlrun] 2020-03-15 21:11:18,975 get pod mlrun-build-my-trainer-tkh7f status
[mlrun] 2020-03-15 21:11:18,984 pod state=pending
10.200.0.50 - - [15/Mar/2020 21:11:18] "GET /api/build/status/?name=my-trainer&project=&tag=&logs=yes&offset=0 HTTP/1.1" 200 -
10.200.0.50 - - [15/Mar/2020 21:11:20] "GET /api/build/status?name=my-trainer&project=&tag=&logs=yes&offset=0 HTTP/1.1" 308 -
[2020-03-15 21:11:21,008] ERROR in app: Exception on /api/build/status/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mlrun/mlrun/db/httpd.py", line 130, in wrapper
    return fn(*args, **kw)
  File "/mlrun/mlrun/db/httpd.py", line 393, in build_status
    fn = _db.get_function(name, project, tag)
  File "/mlrun/mlrun/db/sqldb.py", line 414, in get_function
    obj = query.one_or_none()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3336, in one_or_none
    "Multiple rows were found for one_or_none()"
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one_or_none()
10.200.0.50 - - [15/Mar/2020 21:11:21] "GET /api/build/status/?name=my-trainer&project=&tag=&logs=yes&offset=0 HTTP/1.1" 500 -
[2020-03-15 21:11:21,014] ERROR in app: Exception on /api/build/status/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mlrun/mlrun/db/httpd.py", line 130, in wrapper
    return fn(*args, **kw)
  File "/mlrun/mlrun/db/httpd.py", line 393, in build_status
    fn = _db.get_function(name, project, tag)
  File "/mlrun/mlrun/db/sqldb.py", line 414, in get_function
    obj = query.one_or_none()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3336, in one_or_none
    "Multiple rows were found for one_or_none()"
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one_or_none()
10.200.0.50 - - [15/Mar/2020 21:11:21] "GET /api/build/status/?name=my-trainer&project=&tag=&logs=yes&offset=0 HTTP/1.1" 500 -
[mlrun] 2020-03-15 21:11:22,199 running periodic task
[mlrun] 2020-03-15 21:11:22,220 scheduler loop at 2020-03-15 21:11:22.219975
[2020-03-15 21:11:23,021] ERROR in app: Exception on /api/build/status/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mlrun/mlrun/db/httpd.py", line 130, in wrapper
    return fn(*args, **kw)
  File "/mlrun/mlrun/db/httpd.py", line 393, in build_status
    fn = _db.get_function(name, project, tag)
  File "/mlrun/mlrun/db/sqldb.py", line 414, in get_function
    obj = query.one_or_none()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3336, in one_or_none
    "Multiple rows were found for one_or_none()"
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one_or_none()
10.200.0.50 - - [15/Mar/2020 21:11:23] "GET /api/build/status/?name=my-trainer&project=&tag=&logs=yes&offset=0 HTTP/1.1" 500 -
[2020-03-15 21:11:27,029] ERROR in app: Exception on /api/build/status/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mlrun/mlrun/db/httpd.py", line 130, in wrapper
    return fn(*args, **kw)
  File "/mlrun/mlrun/db/httpd.py", line 393, in build_status
    fn = _db.get_function(name, project, tag)
  File "/mlrun/mlrun/db/sqldb.py", line 414, in get_function
    obj = query.one_or_none()
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3336, in one_or_none
    "Multiple rows were found for one_or_none()"
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one_or_none()
10.200.0.50 - - [15/Mar/2020 21:11:27] "GET /api/build/status/?name=my-trainer&project=&tag=&logs=yes&offset=0 HTTP/1.1" 500 -
```

**Comment by Hedingber** [comment]
Resolved long time ago when we moved from flask to FastAPI, closing
