### ISSUE TITLE
[Bug]: Pickle protocol error

### ISSUE THREAD

**Issue by nikitosl** [mlrun/mlrun#2505]
### MLRun Version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of the MLRun Kit.

### Reproducible Example

```python
quick-start/quick-start.ipynb
```

### Issue Description

Cell `mlrun.deploy_function(serving_fn)` throw next error:

```
Failed to deploy. Details:
22.10.20 13:28:42.978 [37m                processor[0m [34m(I)[0m Starting processor {"version": "Label: 1.9.0, Git commit: 37096462b8b3a1faa2d8e5a84a41e35de55b6c20, OS: linux, Arch: amd64, Go version: go1.17.10"}
22.10.20 13:28:42.978 [37m                processor[0m [32m(D)[0m Read configuration {"config": "{
    "metadata": {
        "name": "breast-cancer-jovyan-serving",
        "namespace": "mlrun",
        "labels": {
            "mlrun/class": "serving",
            "nuclio.io/app": "functionres",
            "nuclio.io/class": "function",
            "nuclio.io/function-name": "breast-cancer-jovyan-serving",
            "nuclio.io/function-version": "latest",
            "nuclio.io/project-name": "breast-cancer-jovyan"
        },
        "annotations": {
            "nuclio.io/generated_by": "function generated from serving.py"
        }
    },
    "spec": {
        "handler": "serving:handler",
        "runtime": "python:3.7",
        "env": [
            {
                "name": "MLRUN_DEFAULT_PROJECT",
                "value": "breast-cancer-jovyan"
            },
            {
                "name": "MLRUN_DBPATH",
                "value": "http://mlrun-api:8080"
            },
            {
                "name": "MLRUN_NAMESPACE",
                "value": "mlrun"
            },
            {
                "name": "SERVING_SPEC_ENV",
                "value": "{\"function_uri\": \"breast-cancer-jovyan/serving\", \"version\": \"v2\", \"parameters\": {}, \"graph\": {\"kind\": \"router\", \"routes\": {\"cancer-classifier\": {\"kind\": \"task\", \"class_name\": \"ClassifierModel\", \"class_args\": {\"model_path\": \"store://artifacts/breast-cancer-jovyan/cancer_classifier:3e98574b5e8d4ef5b5222831ec579c78\"}}}}, \"load_mode\": null, \"functions\": {}, \"graph_initializer\": null, \"error_stream\": null, \"track_models\": null, \"default_content_type\": null}"
            }
        ],
        "resources": {
            "requests": {
                "cpu": "25m",
                "memory": "1Mi"
            }
        },
        "image": "<example.com>/mlrun/processor-breast-cancer-jovyan-serving:latest",
        "imageHash": "1666272450312726328",
        "minReplicas": 1,
        "maxReplicas": 4,
        "triggers": {
            "default-http": {
                "class": "",
                "kind": "http",
                "name": "default-http",
                "maxWorkers": 1,
                "attributes": {
                    "serviceType": "NodePort"
                }
            }
        },
        "volumes": [
            {
                "volume": {
                    "name": "shared-persistency",
                    "persistentVolumeClaim": {
                        "claimName": "mlrun-kit-shared-pvc"
                    }
                },
                "volumeMount": {
                    "name": "shared-persistency",
                    "mountPath": "/home/jovyan/data"
                }
            }
        ],
        "version": -1,
        "alias": "latest",
        "build": {
            "functionSourceCode": "ZnJvbSB0eXBpbmcgaW1wb3J0IExpc3QKCmltcG9ydCBudW1weSBhcyBucApmcm9tIGNsb3VkcGlja2xlIGltcG9ydCBsb2FkCgppbXBvcnQgbWxydW4KCgpjbGFzcyBDbGFzc2lmaWVyTW9kZWwobWxydW4uc2VydmluZy5WMk1vZGVsU2VydmVyKToKICAgIGRlZiBsb2FkKHNlbGYpOgogICAgICAgICIiImxvYWQgYW5kIGluaXRpYWxpemUgdGhlIG1vZGVsIGFuZC9vciBvdGhlciBlbGVtZW50cyIiIgogICAgICAgIG1vZGVsX2ZpbGUsIGV4dHJhX2RhdGEgPSBzZWxmLmdldF9tb2RlbCgiLnBrbCIpCiAgICAgICAgc2VsZi5tb2RlbCA9IGxvYWQob3Blbihtb2RlbF9maWxlLCAicmIiKSkKCiAgICBkZWYgcHJlZGljdChzZWxmLCBib2R5OiBkaWN0KSAtPiBMaXN0OgogICAgICAgICIiIkdlbmVyYXRlIG1vZGVsIHByZWRpY3Rpb25zIGZyb20gc2FtcGxlLiIiIgogICAgICAgIGZlYXRzID0gbnAuYXNhcnJheShib2R5WyJpbnB1dHMiXSkKICAgICAgICByZXN1bHQ6IG5wLm5kYXJyYXkgPSBzZWxmLm1vZGVsLnByZWRpY3QoZmVhdHMpCiAgICAgICAgcmV0dXJuIHJlc3VsdC50b2xpc3QoKQoKZnJvbSBtbHJ1bi5ydW50aW1lcyBpbXBvcnQgbnVjbGlvX2luaXRfaG9vawpkZWYgaW5pdF9jb250ZXh0KGNvbnRleHQpOgogICAgbnVjbGlvX2luaXRfaG9vayhjb250ZXh0LCBnbG9iYWxzKCksICdzZXJ2aW5nX3YyJykKCmRlZiBoYW5kbGVyKGNvbnRleHQsIGV2ZW50KToKICAgIHJldHVybiBjb250ZXh0Lm1scnVuX2hhbmRsZXIoY29udGV4dCwgZXZlbnQpCg==",
            "registry": "<example.com>/mlrun",
            "baseImage": "mlrun/mlrun:1.0.5",
            "codeEntryType": "sourceCode",
            "timestamp": 1666272510
        },
        "runRegistry": "<example.com>/mlrun",
        "imagePullSecrets": "registry-credentials",
        "platform": {},
        "serviceType": "NodePort",
        "securityContext": {},
        "eventTimeout": "",
        "preemptionMode": "prevent"
    },
    "PlatformConfig": null
}", "platformConfig": "{
    "kind": "kube",
    "webAdmin": {},
    "healthCheck": {},
    "logger": {
        "sinks": {
            "myStdoutLoggerSink": {
                "kind": "stdout",
                "attributes": {
                    "encoding": "console",
                    "timeFieldEncoding": "iso8601",
                    "timeFieldName": "time"
                }
            }
        },
        "system": [
            {
                "level": "debug",
                "sink": "myStdoutLoggerSink"
            }
        ],
        "functions": [
            {
                "level": "debug",
                "sink": "myStdoutLoggerSink"
            }
        ]
    },
    "metrics": {},
    "scaleToZero": {
        "multiTargetStrategy": "random"
    },
    "autoScale": {},
    "cronTriggerCreationMode": "processor",
    "functionReadinessTimeout": "2m0s",
    "ingressConfig": {},
    "kube": {
        "defaultServiceType": "ClusterIP",
        "defaultFunctionPodResources": {
            "requests": {},
            "limits": {}
        }
    },
    "local": {
        "FunctionContainersHealthinessEnabled": false,
        "FunctionContainersHealthinessTimeout": 5000000000,
        "FunctionContainersHealthinessInterval": 30000000000
    },
    "imageRegistryOverrides": {},
    "opa": {
        "address": "127.0.0.1:8181",
        "clientKind": "nop",
        "requestTimeout": 10,
        "permissionQueryPath": "/v1/data/iguazio/authz/allow",
        "permissionFilterPath": "/v1/data/iguazio/authz/filter_allowed"
    },
    "streamMonitoring": {
        "webapiURL": "http://v3io-webapi:8081",
        "v3ioRequestConcurrency": 64
    }
}"}
22.10.20 13:28:42.979 [37mcessor.healthcheck.server[0m [34m(I)[0m Listening {"listenAddress": ":8082"}
22.10.20 13:28:42.980 [37m           processor.http[0m [32m(D)[0m Creating worker pool {"num": 1}
22.10.20 13:28:42.993 [37msor.http.w0.python.logger[0m [32m(D)[0m Creating listener socket {"path": "/tmp/nuclio-rpc-cd8kq2nimgctclo11a0g.sock"}
22.10.20 13:28:42.993 [37msor.http.w0.python.logger[0m [32m(D)[0m Using Python wrapper script path {"path": "/opt/nuclio/_nuclio_wrapper.py"}
22.10.20 13:28:42.993 [37msor.http.w0.python.logger[0m [32m(D)[0m Using Python handler {"handler": "serving:handler"}
22.10.20 13:28:42.993 [37msor.http.w0.python.logger[0m [32m(D)[0m Using Python executable {"path": "/usr/local/bin/python3"}
22.10.20 13:28:42.993 [37msor.http.w0.python.logger[0m [32m(D)[0m Setting PYTHONPATH {"value": "PYTHONPATH=/opt/nuclio"}
22.10.20 13:28:42.993 [37msor.http.w0.python.logger[0m [32m(D)[0m Running wrapper {"command": "/usr/local/bin/python3 -u /opt/nuclio/_nuclio_wrapper.py --handler serving:handler --socket-path /tmp/nuclio-rpc-cd8kq2nimgctclo11a0g.sock --platform-kind kube --namespace mlrun --worker-id 0 --trigger-kind http --trigger-name default-http --decode-event-strings"}
22.10.20 13:28:46.554 [37msor.http.w0.python.logger[0m [34m(I)[0m Wrapper connected {"wid": 0, "pid": 16}
22.10.20 13:28:46.555 [37msor.http.w0.python.logger[0m [32m(D)[0m Waiting for start
22.10.20 13:28:46.629 [37msor.http.w0.python.logger[0m [31m(E)[0m Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mlrun/serving/v2_serving.py", line 129, in _load_and_update_state
    self.load()
  File "/opt/nuclio/serving.py", line 13, in load
    self.model = load(open(model_file, "rb"))
ValueError: unsupported pickle protocol: 5
 {"worker_id": "0"}
22.10.20 13:28:46.630 [37msor.http.w0.python.logger[0m [31m(E)[0m Exception raised while running init_context {"worker_id": "0"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mlrun/serving/v2_serving.py", line 129, in _load_and_update_state
    self.load()
  File "/opt/nuclio/serving.py", line 13, in load
    self.model = load(open(model_file, "rb"))
ValueError: unsupported pickle protocol: 5

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/nuclio/_nuclio_wrapper.py", line 437, in <module>
    run_wrapper()
  File "/opt/nuclio/_nuclio_wrapper.py", line 425, in run_wrapper
    loop.run_until_complete(wrapper_instance.initialize())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/opt/nuclio/_nuclio_wrapper.py", line 151, in initialize
    await self._initialize_context()
  File "/opt/nuclio/_nuclio_wrapper.py", line 162, in _initialize_context
    init_context_result = getattr(self._entrypoint_module, 'init_context')(self._context)
  File "/opt/nuclio/serving.py", line 23, in init_context
    nuclio_init_hook(context, globals(), 'serving_v2')
  File "/usr/local/lib/python3.7/site-packages/mlrun/runtimes/nuclio.py", line 32, in nuclio_init_hook
    v2_serving_init(context, data)
  File "/usr/local/lib/python3.7/site-packages/mlrun/serving/server.py", line 312, in v2_serving_init
    serving_handler = server.init_object(namespace or get_caller_globals())
  File "/usr/local/lib/python3.7/site-packages/mlrun/serving/server.py", line 174, in init_object
    self.graph.init_object(self.context, namespace, self.load_mode, reset=True)
  File "/usr/local/lib/python3.7/site-packages/mlrun/serving/states.py", line 571, in init_object
    route.init_object(context, namespace, mode, reset=reset)
  File "/usr/local/lib/python3.7/site-packages/mlrun/serving/states.py", line 403, in init_object
    self._post_init(mode)
  File "/usr/local/lib/python3.7/site-packages/mlrun/serving/states.py", line 428, in _post_init
    self._object.post_init(mode)
  File "/usr/local/lib/python3.7/site-packages/mlrun/serving/v2_serving.py", line 145, in post_init
    self._load_and_update_state()
  File "/usr/local/lib/python3.7/site-packages/mlrun/serving/v2_serving.py", line 133, in _load_and_update_state
    raise RuntimeError(f"failed to load model {self.name}, {exc}")
RuntimeError: failed to load model cancer-classifier, unsupported pickle protocol: 5
22.10.20 13:28:47.372 [37msor.http.w0.python.logger[0m [33m(W)[0m Failed to read from connection {"err": "EOF"}
22.10.20 13:28:47.372 [37msor.http.w0.python.logger[0m [31m(E)[0m Unexpected termination of child process {"error": null, "status": "exit status 1"}
```

### Expected Behavior

Deploy model to mlrun

### Python Version

3.8.8 

### MLRun Version

1.0.5

### Additional Information

MLrun was newly deployed on kubernetes cluster following the instructions. All function in this notebook before deploying model worked correctly.

**Comment by nikitosl** [comment]
Hello, @Tankilevitch ! Thanks for your help!
I tried your suggestion:
```
serving_fn = mlrun.code_to_function("serving", 
                                    image="python:3.8", 
                                    filename="serving.py", 
                                    kind="serving", 
                                    requirements=["mlrun[complete]"])
```

Now deploy_function(serving_fn) throw another error: `No module named 'sklearn'`:
```
File "/usr/local/lib/python3.8/site-packages/mlrun/serving/v2_serving.py", line 130, in _load_and_update_state
    self.load()
  File "/opt/nuclio/serving.py", line 13, in load
    self.model = load(open(model_file, "rb"))
ModuleNotFoundError: No module named 'sklearn'
 {"worker_id": "0"}
22.10.26 08:20:12.042 [37msor.http.w0.python.logger[0m [31m(E)[0m Exception raised while running init_context {"worker_id": "0"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/mlrun/serving/v2_serving.py", line 130, in _load_and_update_state
    self.load()
  File "/opt/nuclio/serving.py", line 13, in load
    self.model = load(open(model_file, "rb"))
ModuleNotFoundError: No module named 'sklearn'
```
Looks like it lost requirements from mlrun/mlrun image..

**Comment by nikitosl** [comment]
I added sklearn to requirements:
```
serving_fn = mlrun.code_to_function("serving", 
                                    image="python:3.8", 
                                    filename="serving.py", 
                                    kind="serving", 
                                    requirements=["mlrun[complete]", "scikit-learn==1.1.2"])
```
And successfully deployed model!
Thank you!
