### ISSUE TITLE
[Bug]: MLRun CE 1.5.0 - V3IO_ACCESS_KEY is required for Parquet target

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#4487]
### MLRun Version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of MLRun CE.

### Reproducible Example

```python
import mlrun
import mlrun.feature_store as fstore
import sys, time, pandas, numpy

def test(name):
    project_name = "my-project"
    feature_name = "fs-01"

    mlrun.set_env_from_file("mlrun-nonprod.env")

    project = mlrun.get_or_create_project(project_name, context='./', user_project=False)

    try:
        # get existing feature set
        feature_set = fstore.get_feature_set(f"{project_name}/{feature_name}")
    except:
        # create new feature set
        feature_set = fstore.FeatureSet(feature_name, entities=[fstore.Entity("fn0", description='fn0 description'),
                                                                fstore.Entity("fn1",
                                                                              value_type=mlrun.data_types.data_types.ValueType.STRING,
                                                                              description='fn1 description')],
                                        engine="storey")
        feature_set.set_targets(targets=[mlrun.datastore.ParquetTarget()], with_defaults=False)
        feature_set.save()

    # generate sample data
    dataFrm = pandas.DataFrame(numpy.random.randint(low=0, high=1000,
                                                    size=(100, 10)),  # rows, columns
                               columns=[f"fn{i}" for i in range(10)])

    # print header of sample data
    # print(dataFrm.head(2))

    # print size of data
    print('DataFrame size: ' + str(round(sys.getsizeof(dataFrm) / (1024 * 1024), 2)) + '/' + \
          str(round(sys.getsizeof(dataFrm) / (1024), 2)) + ' [MB/KB], ' + \
          'Rows: ' + str(len(dataFrm)))

    fstore.ingest(feature_set,dataFrm, overwrite=True)

if __name__ == '__main__':
    test('PyCharm')
```

### Issue Description

I got this mistake
`ValueError: Access key must be provided in Client() arguments or in the V3IO_ACCESS_KEY environment variable`

for:
- data ingest, to the FeatureSet only with ParquetTarget 

See call stack:
```
Traceback (most recent call last):
  File "C:\Python\mlrunce-ingest\venv\lib\site-packages\mlrun\serving\states.py", line 420, in init_object
    self._object = self._class_object(**extracted_class_args)
  File "C:\Python\mlrunce-ingest\venv\lib\site-packages\storey\targets.py", line 565, in __init__
    self._file_system, self._path = url_to_file_system(path, storage_options)
  File "C:\Python\mlrunce-ingest\venv\lib\site-packages\storey\utils.py", line 151, in url_to_file_system
    return fsspec.filesystem(scheme, **storage_options), remaining_path
  File "C:\Python\mlrunce-ingest\venv\lib\site-packages\fsspec\registry.py", line 267, in filesystem
    return cls(**storage_options)
  File "C:\Python\mlrunce-ingest\venv\lib\site-packages\fsspec\spec.py", line 79, in __call__
    obj = super().__call__(*args, **kwargs)
  File "C:\Python\mlrunce-ingest\venv\lib\site-packages\v3iofs\fs.py", line 108, in __init__
    self._client = _new_client(v3io_api, v3io_access_key)
  File "C:\Python\mlrunce-ingest\venv\lib\site-packages\v3iofs\fs.py", line 457, in _new_client
    return Client(
  File "C:\Python\mlrunce-ingest\venv\lib\site-packages\v3io\dataplane\client.py", line 92, in __init__
    raise ValueError(
ValueError: Access key must be provided in Client() arguments or in the V3IO_ACCESS_KEY environment variable
```

### Expected Behavior

V3IO_ACCESS_KEY is not required for ParquetTarget in MLRun CE 

### Installation OS

Windows

### Installation Method

Docker

### Python Version

3.9.13

### MLRun Version

1.5.0 (version from 23.10.2023)

**Comment by xsqian** [comment]
Hi Jiri,

We are looking into the fix for the issue. In the meantime, there is workaround for now. 
Looks like the target is created with a default path since no path is given on initialization, and the default path for some reason points at v3io:///...:
feature_set.set_targets(targets=[mlrun.datastore.ParquetTarget()],
The easiest workaround would be to provide a path there - mlrun.datastore.ParquetTarget(path='<local path>') .

Please let us know if the workaround works for you.

Regards,
Xingsheng

**Comment by george0st** [comment]
Hi @xsqian , this work-around works, thx for that. I tested these settings: 

- mlrun.datastore.ParquetTarget(path="./") - **it works**
- mlrun.datastore.ParquetTarget(path="c:\\test\\") - **it works**
- mlrun.datastore.ParquetTarget(path="") - **error with V3IO_ACCESS_KEY**

BTW: it will be useful to use 

- default path with v3io only in case of Iguazio platform (if V3IO_ACCESS_KEY exists)
- and default path "./" in case for MLRun CE (if V3IO_ACCESS_KEY not exists)

**Comment by george0st** [comment]
I am closing this point, workaround exist.
