### ISSUE TITLE
[Bug]: can't import mlrun because of missing dependency

### ISSUE THREAD

**Issue by fschlz** [mlrun/mlrun#5291]
### MLRun Version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of MLRun CE.

### Reproducible Example

```bash
# initialize pyproject.toml
>>> poetry init

# add dependencies in pyproject.toml
>>> code pyproject.toml

[tool.poetry]
name = "learn-mlrun"
version = "0.1.0"
description = ""

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
mlrun = "^1.6.1"
pyyaml = { version = "!=6.0.0,!=5.4.0,!=5.4.1" }

[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# start notebook to test mlrun
>>> code test.ipynb
import mlrun # throws error
```

### Issue Description

Importing mlrun in a notebook after installing it throws the following error:

<img width="673" alt="image" src="https://github.com/mlrun/mlrun/assets/22344801/c1610538-0213-4821-bf47-20611e7896ee">

Trying to install protobuf via poetry leads to issues with dependency resolution:

```bash

    Because no versions of mlrun match >1.6.1,<1.6.2rc1 || >1.6.2rc1,<1.6.2rc2 || >1.6.2rc2,<1.6.2rc3 || >1.6.2rc3,<1.7.0rc1 || >1.7.0rc1,<1.7.0rc2 || >1.7.0rc2,<1.7.0rc3 || >1.7.0rc3,<1.7.0rc4 || >1.7.0rc4,<1.7.0rc5 || >1.7.0rc5,<2.0.0
 and mlrun (1.6.2rc1) depends on kfp (>=1.8,<2.0), mlrun (>1.6.1,<1.6.2rc2 || >1.6.2rc2,<1.6.2rc3 || >1.6.2rc3,<1.7.0rc1 || >1.7.0rc1,<1.7.0rc2 || >1.7.0rc2,<1.7.0rc3 || >1.7.0rc3,<1.7.0rc4 || >1.7.0rc4,<1.7.0rc5 || >1.7.0rc5,<2.0.0) requires kfp (>=1.8,<2.0).
    And because mlrun (1.6.2rc2) depends on kfp (>=1.8,<2.0)
 and mlrun (1.6.2rc3) depends on kfp (>=1.8,<2.0), mlrun (>1.6.1,<1.7.0rc1 || >1.7.0rc1,<1.7.0rc2 || >1.7.0rc2,<1.7.0rc3 || >1.7.0rc3,<1.7.0rc4 || >1.7.0rc4,<1.7.0rc5 || >1.7.0rc5,<2.0.0) requires kfp (>=1.8,<2.0).
    And because mlrun (1.7.0rc1) depends on kfp (>=1.8,<2.0)
 and mlrun (1.7.0rc2) depends on kfp (>=1.8,<2.0), mlrun (>1.6.1,<1.7.0rc3 || >1.7.0rc3,<1.7.0rc4 || >1.7.0rc4,<1.7.0rc5 || >1.7.0rc5,<2.0.0) requires kfp (>=1.8,<2.0).
    And because mlrun (1.7.0rc3) depends on kfp (>=1.8,<2.0)
 and mlrun (1.7.0rc4) depends on kfp (>=1.8,<2.0), mlrun (>1.6.1,<1.7.0rc5 || >1.7.0rc5,<2.0.0) requires kfp (>=1.8,<2.0).
(1) So, because mlrun (1.7.0rc5) depends on kfp (>=1.8,<2.0)
 and mlrun (1.6.1) depends on kfp (>=1.8,<2.0), mlrun (>=1.6.1,<2.0.0) requires kfp (>=1.8,<2.0).

    Because no versions of kfp match >1.8,<1.8.1 || >1.8.1,<1.8.2 || >1.8.2,<1.8.3 || >1.8.3,<1.8.4 || >1.8.4,<1.8.5 || >1.8.5,<1.8.6 || >1.8.6,<1.8.7 || >1.8.7,<1.8.8 || >1.8.8,<1.8.9 || >1.8.9,<1.8.10 || >1.8.10,<1.8.11 || >1.8.11,<1.8.12 || >1.8.12,<1.8.13 || >1.8.13,<1.8.14 || >1.8.14,<1.8.15 || >1.8.15,<1.8.16 || >1.8.16,<1.8.17 || >1.8.17,<1.8.18 || >1.8.18,<1.8.19 || >1.8.19,<1.8.20 || >1.8.20,<1.8.21 || >1.8.21,<1.8.22 || >1.8.22,<2.0
 and kfp (1.8.0) depends on protobuf (>=3.13.0,<4), kfp (>=1.8,<1.8.1 || >1.8.1,<1.8.2 || >1.8.2,<1.8.3 || >1.8.3,<1.8.4 || >1.8.4,<1.8.5 || >1.8.5,<1.8.6 || >1.8.6,<1.8.7 || >1.8.7,<1.8.8 || >1.8.8,<1.8.9 || >1.8.9,<1.8.10 || >1.8.10,<1.8.11 || >1.8.11,<1.8.12 || >1.8.12,<1.8.13 || >1.8.13,<1.8.14 || >1.8.14,<1.8.15 || >1.8.15,<1.8.16 || >1.8.16,<1.8.17 || >1.8.17,<1.8.18 || >1.8.18,<1.8.19 || >1.8.19,<1.8.20 || >1.8.20,<1.8.21 || >1.8.21,<1.8.22 || >1.8.22,<2.0) requires protobuf (>=3.13.0,<4).
    And because kfp (1.8.1) depends on protobuf (>=3.13.0,<4)
 and kfp (1.8.2) depends on protobuf (>=3.13.0,<4), kfp (>=1.8,<1.8.3 || >1.8.3,<1.8.4 || >1.8.4,<1.8.5 || >1.8.5,<1.8.6 || >1.8.6,<1.8.7 || >1.8.7,<1.8.8 || >1.8.8,<1.8.9 || >1.8.9,<1.8.10 || >1.8.10,<1.8.11 || >1.8.11,<1.8.12 || >1.8.12,<1.8.13 || >1.8.13,<1.8.14 || >1.8.14,<1.8.15 || >1.8.15,<1.8.16 || >1.8.16,<1.8.17 || >1.8.17,<1.8.18 || >1.8.18,<1.8.19 || >1.8.19,<1.8.20 || >1.8.20,<1.8.21 || >1.8.21,<1.8.22 || >1.8.22,<2.0) requires protobuf (>=3.13.0,<4).
    And because kfp (1.8.3) depends on protobuf (>=3.13.0,<4)
 and kfp (1.8.4) depends on protobuf (>=3.13.0,<4), kfp (>=1.8,<1.8.5 || >1.8.5,<1.8.6 || >1.8.6,<1.8.7 || >1.8.7,<1.8.8 || >1.8.8,<1.8.9 || >1.8.9,<1.8.10 || >1.8.10,<1.8.11 || >1.8.11,<1.8.12 || >1.8.12,<1.8.13 || >1.8.13,<1.8.14 || >1.8.14,<1.8.15 || >1.8.15,<1.8.16 || >1.8.16,<1.8.17 || >1.8.17,<1.8.18 || >1.8.18,<1.8.19 || >1.8.19,<1.8.20 || >1.8.20,<1.8.21 || >1.8.21,<1.8.22 || >1.8.22,<2.0) requires protobuf (>=3.13.0,<4).
    And because kfp (1.8.5) depends on protobuf (>=3.13.0,<4)
 and kfp (1.8.6) depends on protobuf (>=3.13.0,<4), kfp (>=1.8,<1.8.7 || >1.8.7,<1.8.8 || >1.8.8,<1.8.9 || >1.8.9,<1.8.10 || >1.8.10,<1.8.11 || >1.8.11,<1.8.12 || >1.8.12,<1.8.13 || >1.8.13,<1.8.14 || >1.8.14,<1.8.15 || >1.8.15,<1.8.16 || >1.8.16,<1.8.17 || >1.8.17,<1.8.18 || >1.8.18,<1.8.19 || >1.8.19,<1.8.20 || >1.8.20,<1.8.21 || >1.8.21,<1.8.22 || >1.8.22,<2.0) requires protobuf (>=3.13.0,<4).
    And because kfp (1.8.7) depends on protobuf (>=3.13.0,<4)
 and kfp (1.8.8) depends on protobuf (>=3.13.0,<4), kfp (>=1.8,<1.8.9 || >1.8.9,<1.8.10 || >1.8.10,<1.8.11 || >1.8.11,<1.8.12 || >1.8.12,<1.8.13 || >1.8.13,<1.8.14 || >1.8.14,<1.8.15 || >1.8.15,<1.8.16 || >1.8.16,<1.8.17 || >1.8.17,<1.8.18 || >1.8.18,<1.8.19 || >1.8.19,<1.8.20 || >1.8.20,<1.8.21 || >1.8.21,<1.8.22 || >1.8.22,<2.0) requires protobuf (>=3.13.0,<4).
    And because kfp (1.8.9) depends on protobuf (>=3.13.0,<4)
 and kfp (1.8.10) depends on protobuf (>=3.13.0,<4), kfp (>=1.8,<1.8.11 || >1.8.11,<1.8.12 || >1.8.12,<1.8.13 || >1.8.13,<1.8.14 || >1.8.14,<1.8.15 || >1.8.15,<1.8.16 || >1.8.16,<1.8.17 || >1.8.17,<1.8.18 || >1.8.18,<1.8.19 || >1.8.19,<1.8.20 || >1.8.20,<1.8.21 || >1.8.21,<1.8.22 || >1.8.22,<2.0) requires protobuf (>=3.13.0,<4).
    And because kfp (1.8.11) depends on protobuf (>=3.13.0,<4)
 and kfp (1.8.12) depends on protobuf (>=3.13.0,<4), kfp (>=1.8,<1.8.13 || >1.8.13,<1.8.14 || >1.8.14,<1.8.15 || >1.8.15,<1.8.16 || >1.8.16,<1.8.17 || >1.8.17,<1.8.18 || >1.8.18,<1.8.19 || >1.8.19,<1.8.20 || >1.8.20,<1.8.21 || >1.8.21,<1.8.22 || >1.8.22,<2.0) requires protobuf (>=3.13.0,<4).
    And because kfp (1.8.13) depends on protobuf (>=3.13.0,<4)
 and kfp (1.8.14) depends on protobuf (>=3.13.0,<4), kfp (>=1.8,<1.8.15 || >1.8.15,<1.8.16 || >1.8.16,<1.8.17 || >1.8.17,<1.8.18 || >1.8.18,<1.8.19 || >1.8.19,<1.8.20 || >1.8.20,<1.8.21 || >1.8.21,<1.8.22 || >1.8.22,<2.0) requires protobuf (>=3.13.0,<4).
    And because kfp (1.8.15) depends on protobuf (>=3.13.0,<4)
 and kfp (1.8.16) depends on protobuf (>=3.13.0,<4), kfp (>=1.8,<1.8.17 || >1.8.17,<1.8.18 || >1.8.18,<1.8.19 || >1.8.19,<1.8.20 || >1.8.20,<1.8.21 || >1.8.21,<1.8.22 || >1.8.22,<2.0) requires protobuf (>=3.13.0,<4).
    And because kfp (1.8.17) depends on protobuf (>=3.13.0,<4)
 and kfp (1.8.18) depends on protobuf (>=3.13.0,<4), kfp (>=1.8,<1.8.19 || >1.8.19,<1.8.20 || >1.8.20,<1.8.21 || >1.8.21,<1.8.22 || >1.8.22,<2.0) requires protobuf (>=3.13.0,<4).
    And because kfp (1.8.19) depends on protobuf (>=3.13.0,<4)
 and kfp (1.8.20) depends on protobuf (>=3.13.0,<4), kfp (>=1.8,<1.8.21 || >1.8.21,<1.8.22 || >1.8.22,<2.0) requires protobuf (>=3.13.0,<4).
    And because kfp (1.8.21) depends on protobuf (>=3.13.0,<4)
 and kfp (1.8.22) depends on protobuf (>=3.13.0,<4), kfp (>=1.8,<2.0) requires protobuf (>=3.13.0,<4).
    And because mlrun (>=1.6.1,<2.0.0) requires kfp (>=1.8,<2.0) (1), mlrun (>=1.6.1,<2.0.0) requires protobuf (>=3.13.0,<4)
    So, because learn-mlrun depends on both mlrun (^1.6.1) and protobuf (^5.26.0), version solving failed.
```

### Expected Behavior

I would expect all dependencies to be declared and installed.

### Installation OS

Mac

### Installation Method

Docker

### Python Version

3.10.13

### MLRun Version

1.6.1

**Comment by fschlz** [comment]
I also saw this article: https://docs.mlrun.org/en/latest/install/remote.html#set-up-your-environment
Tried using Python 3.9, same result.

The protobuf version that gets installed alongside mlrun is pretty old, though. (3.20.3)
Perhaps an upgrade to a newer version is necessary. (latest: 5.26.0)

**Comment by alonmr** [comment]
Hey @fschlz , the protobuf version we use is not supported on arm64 so we use a conda environment to emulate x86_64.
I'm assuming you have arm64 mac and that you are using python venv by the description of the issue. If that is the case, please use a conda env instead. Using conda on top of arm64 is required for now until all of our dependencies will work smoothly on both architectures with python venv. Currently we cannot upgrade protobuf due to the following issue - https://stackoverflow.com/questions/72441758/typeerror-descriptors-cannot-not-be-created-directly

**Comment by antonymilne** [comment]
Unfortunately I am getting same on my x86_64 Mac - any ideas? 🙏 
```
➜ uname -m
x86_64

➜ uv venv --python 3.9 && source .venv/bin/activate && uv pip install mlrun
Using CPython 3.9.6 interpreter at: /Library/Developer/CommandLineTools/usr/bin/python3
Creating virtual environment at: .venv
Activate with: source .venv/bin/activate
```

Then:
```
➜ python -c "import mlrun"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/antony_milne/vizro_stuff/demo-call-center/.venv/lib/python3.9/site-packages/mlrun/__init__.py", line 32, in <module>
    from .datastore import DataItem, store_manager
  File "/Users/antony_milne/vizro_stuff/demo-call-center/.venv/lib/python3.9/site-packages/mlrun/datastore/__init__.py", line 48, in <module>
    from .base import DataItem
  File "/Users/antony_milne/vizro_stuff/demo-call-center/.venv/lib/python3.9/site-packages/mlrun/datastore/base.py", line 35, in <module>
    from .store_resources import is_store_uri, parse_store_uri
  File "/Users/antony_milne/vizro_stuff/demo-call-center/.venv/lib/python3.9/site-packages/mlrun/datastore/store_resources.py", line 25, in <module>
    from .targets import get_online_target
  File "/Users/antony_milne/vizro_stuff/demo-call-center/.venv/lib/python3.9/site-packages/mlrun/datastore/targets.py", line 34, in <module>
    from mlrun.utils.v3io_clients import get_frames_client
  File "/Users/antony_milne/vizro_stuff/demo-call-center/.venv/lib/python3.9/site-packages/mlrun/utils/v3io_clients.py", line 18, in <module>
    from v3io_frames import Client as get_client
  File "/Users/antony_milne/vizro_stuff/demo-call-center/.venv/lib/python3.9/site-packages/v3io_frames/__init__.py", line 26, in <module>
    from .grpc import Client as gRPCClient  # noqa
  File "/Users/antony_milne/vizro_stuff/demo-call-center/.venv/lib/python3.9/site-packages/v3io_frames/grpc.py", line 31, in <module>
    from .http import format_go_time
  File "/Users/antony_milne/vizro_stuff/demo-call-center/.venv/lib/python3.9/site-packages/v3io_frames/http.py", line 32, in <module>
    from .pbutils import df2msg, msg2df, pb2py
  File "/Users/antony_milne/vizro_stuff/demo-call-center/.venv/lib/python3.9/site-packages/v3io_frames/pbutils.py", line 18, in <module>
    import google.protobuf.pyext._message as message
ModuleNotFoundError: No module named 'google.protobuf.pyext._message'
```

<details>

<summary>Installed packages - output of `uv pip freeze`</summary>

```
absl-py==1.4.0
aiohappyeyeballs==2.4.3
aiohttp==3.10.8
aiohttp-retry==2.8.3
aiosignal==1.3.1
anyio==3.7.1
appnope==0.1.4
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
async-timeout==4.0.3
attrs==24.2.0
beautifulsoup4==4.12.3
bleach==6.1.0
boto3==1.35.30
botocore==1.35.30
cachetools==5.5.0
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.3.2
click==8.1.7
cloudpickle==2.2.1
comm==0.2.2
debugpy==1.8.6
decorator==5.1.1
defusedxml==0.7.1
dependency-injector==4.42.0
deprecated==1.2.14
docstring-parser==0.16
entrypoints==0.4
exceptiongroup==1.2.2
executing==2.1.0
fastjsonschema==2.20.0
fire==0.7.0
fqdn==1.5.1
frozenlist==1.4.1
fsspec==2023.9.2
future==1.0.0
gitdb==4.0.11
gitpython==3.1.43
google-api-core==2.20.0
google-api-python-client==1.12.11
google-auth==2.35.0
google-auth-httplib2==0.2.0
google-cloud-core==2.4.1
google-cloud-storage==2.18.2
google-crc32c==1.6.0
google-resumable-media==2.7.2
googleapis-common-protos==1.65.0
grpcio==1.66.2
grpcio-tools==1.48.2
httplib2==0.22.0
idna==3.10
importlib-metadata==8.5.0
inflection==0.5.1
ipykernel==6.29.5
ipython==8.18.1
ipython-genutils==0.2.0
isoduration==20.11.0
jedi==0.19.1
jinja2==3.1.4
jmespath==1.0.1
jsonpointer==3.0.0
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
jupyter-client==7.4.9
jupyter-core==5.7.2
jupyter-events==0.10.0
jupyter-server==2.14.2
jupyter-server-terminals==0.5.3
jupyterlab-pygments==0.3.0
kfp==1.8.22
kfp-pipeline-spec==0.1.16
kfp-server-api==1.8.5
kubernetes==25.3.0
markdown-it-py==3.0.0
markupsafe==2.1.5
matplotlib-inline==0.1.7
mdurl==0.1.2
mergedeep==1.3.4
mistune==3.0.2
mlrun==1.6.4
multidict==6.1.0
nbclassic==1.1.0
nbclient==0.10.0
nbconvert==7.16.4
nbformat==5.10.4
nest-asyncio==1.6.0
notebook==6.5.7
notebook-shim==0.2.4
nuclio-jupyter==0.9.17
nuclio-sdk==0.5.13
numpy==1.26.4
oauthlib==3.2.2
orjson==3.10.7
overrides==7.7.0
packaging==24.1
pandas==2.1.4
pandocfilters==1.5.1
parso==0.8.4
pexpect==4.9.0
platformdirs==4.3.6
prometheus-client==0.21.0
prompt-toolkit==3.0.48
proto-plus==1.24.0
protobuf==3.20.3
psutil==6.0.0
ptyprocess==0.7.0
pure-eval==0.2.3
pyarrow==14.0.2
pyasn1==0.6.1
pyasn1-modules==0.4.1
pycparser==2.22
pydantic==1.10.14
pygments==2.18.0
pyparsing==3.1.4
python-dateutil==2.9.0.post0
python-dotenv==0.17.1
python-json-logger==2.0.7
pytz==2024.2
pyyaml==5.4.1
pyzmq==26.2.0
referencing==0.35.1
requests==2.32.3
requests-oauthlib==2.0.0
requests-toolbelt==0.10.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.9.1
rpds-py==0.20.0
rsa==4.9
s3transfer==0.10.2
semver==3.0.2
send2trash==1.8.3
setuptools==69.5.1
shellingham==1.5.4
six==1.16.0
smmap==5.0.1
sniffio==1.3.1
soupsieve==2.6
stack-data==0.6.3
storey==1.6.20
strip-hints==0.1.10
tabulate==0.8.10
termcolor==2.4.0
terminado==0.18.1
tinycss2==1.3.0
tornado==6.4.1
traitlets==5.14.3
typer==0.12.5
types-python-dateutil==2.9.0.20240906
typing-extensions==4.12.2
tzdata==2024.2
uri-template==1.3.0
uritemplate==3.0.1
urllib3==1.26.20
v3io==0.6.10
v3io-frames==0.10.14
v3iofs==0.1.18
wcwidth==0.2.13
webcolors==24.8.0
webencodings==0.5.1
websocket-client==1.8.0
wheel==0.44.0
wrapt==1.16.0
xxhash==3.5.0
yarl==1.13.1
zipp==3.20.2
```
</details>

**Comment by alonmr** [comment]
Hey @antonymilne 
I've never seen this before on x86 machines. Usually it happens on arm64 and then we recommend installing with conda. However, I see you are using uv which might cause this issue. Please try installing `protobuf==3.20.3` with pip and let us know if it helps.
We now have a script that compiles protobuf 3.20.3 on arm64 but it doesn't work with uv which leads me to believe that uv might be the issue. The script is at https://github.com/mlrun/mlrun/blob/development/automation/scripts/compile_protobuf320_for_mac_arm64.sh

**Comment by antonymilne** [comment]
Ah yes, that works (without using conda)! Thank you very much @alonmr 🙏 

```
uv venv --python 3.9 && source .venv/bin/activate && uv pip install mlrun
uv pip uninstall protobuf
uv pip install pip && pip install "protobuf==3.20.3"
```

**Comment by alonmr** [comment]
This will be officially solved in mlrun 1.9 which will support python 3.11
