### ISSUE TITLE
[Bug]: pyarrow.lib.ArrowTypeError: ("Expected bytes, got a 'datetime.date' object", 'Conversion failed for column party-establishment with type object')

### ISSUE THREAD

**Issue by george0st** [mlrun/mlrun#5403]
### MLRun Version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of MLRun CE.

### Reproducible Example

```python
import mlrun
import mlrun.feature_store as fstore
from mlrun.datastore.targets import RedisNoSqlTarget,SQLTarget, CSVTarget, ParquetTarget
from mlrun.datastore.sources import CSVSource, ParquetSource
from mlrun.data_types.data_types import ValueType


def create_featureset(feature_name):

    # https://www.parquet-viewer.com/#parquet-online

    feature_set = fstore.FeatureSet(feature_name, entities=[fstore.Entity("party-id", value_type=ValueType.STRING)],
                                    engine="storey")
    feature_set.add_feature(fstore.Feature(name="party-establishment", value_type=ValueType.DATETIME))
    feature_set.add_feature(fstore.Feature(name="party-type", value_type=ValueType.STRING))
    feature_set.add_feature(fstore.Feature(name="party-typedate", value_type=ValueType.DATETIME))
    feature_set.add_feature(fstore.Feature(name="party-gender", value_type=ValueType.STRING))
    feature_set.add_feature(fstore.Feature(name="party-education", value_type=ValueType.STRING))
    feature_set.add_feature(fstore.Feature(name="party-familystatus", value_type=ValueType.STRING))
    feature_set.add_feature(fstore.Feature(name="party-nchild", value_type=ValueType.INT64))
    feature_set.add_feature(fstore.Feature(name="party-industry", value_type=ValueType.STRING))
    feature_set.add_feature(fstore.Feature(name="party-industryposition", value_type=ValueType.STRING))
    feature_set.add_feature(fstore.Feature(name="party-residencecountry", value_type=ValueType.STRING))
    feature_set.add_feature(fstore.Feature(name="party-city", value_type=ValueType.STRING))
    feature_set.add_feature(fstore.Feature(name="party-income", value_type=ValueType.INT64))
    feature_set.add_feature(fstore.Feature(name="party-incometype", value_type=ValueType.STRING))
    feature_set.add_feature(fstore.Feature(name="party-peoplehousehold", value_type=ValueType.INT64))
    feature_set.add_feature(fstore.Feature(name="party-incomehousehold", value_type=ValueType.INT64))
    feature_set.add_feature(fstore.Feature(name="party-expenseshousehold", value_type=ValueType.INT64))
    feature_set.add_feature(fstore.Feature(name="party-currency", value_type=ValueType.STRING))
    feature_set.add_feature(fstore.Feature(name="record-date", value_type=ValueType.DATETIME))

    return feature_set

def parquet_issue(project_name):

    mlrun.set_env_from_file("mlrun-nonprod.env")
    project = mlrun.get_or_create_project(project_name, context='./', user_project=False)

    # use CSVSource
    feature_name = "basic-party-csv"
    feature_set=create_featureset(feature_name)
    feature_set.set_targets(targets=[ParquetTarget(name="parquet1", path="./output/parq1/")],
                            with_defaults=False)
    feature_set.save()
    feature_set.ingest(CSVSource(name="tst", path="./01-basic-party.csv.gz"),
                  return_df=False,
                  infer_options=mlrun.data_types.data_types.InferOptions.default())


    # use ParquetSource
    feature_name = "basic-party-parquet"
    feature_set=create_featureset(feature_name)
    feature_set.set_targets(targets=[ParquetTarget(name="parquet2", path="./output/parq2/")],
                            with_defaults=False)
    feature_set.save()

    # it generates the issue
    feature_set.ingest(ParquetSource(name="tst", path="./01-basic-party.parquet"),
                  return_df=False,
                  infer_options=mlrun.data_types.data_types.InferOptions.default())


if __name__ == '__main__':

    project="ab3"
    parquet_issue(project)
```

### Issue Description

The exception was generated in case, that Feature type was **ValueType.DATETIME** and I used **ParquetSource** (in case that source is CSVSource all is fine), see exception. I attached also source files for load (please remove from file '01-basic-party.parquet.gz' the suffix .gz).

[01-basic-party.csv.gz](https://github.com/mlrun/mlrun/files/14909212/01-basic-party.csv.gz)
[01-basic-party.parquet.gz](https://github.com/mlrun/mlrun/files/14909215/01-basic-party.parquet.gz)

```
Traceback (most recent call last):
  File "C:\Python\test\main.py", line 627, in <module>
    parquet_issue(project)
  File "C:\Python\test\main.py", line 585, in parquet_issue
    feature_set.ingest(ParquetSource(name="tst", path="./01-basic-party.parquet"),
  File "C:\Python\test\.venv\lib\site-packages\mlrun\feature_store\feature_set.py", line 1039, in ingest
    return mlrun.feature_store.api._ingest(
  File "C:\Python\test\.venv\lib\site-packages\mlrun\feature_store\api.py", line 729, in _ingest
    df = init_featureset_graph(
  File "C:\Python\test\.venv\lib\site-packages\mlrun\feature_store\ingestion.py", line 68, in init_featureset_graph
    return graph.wait_for_completion()
  File "C:\Python\test\.venv\lib\site-packages\mlrun\serving\states.py", line 1188, in wait_for_completion
    return self._controller.await_termination()
  File "C:\Python\test\.venv\lib\site-packages\storey\sources.py", line 233, in await_termination
    return self._await_termination_fn()
  File "C:\Python\test\.venv\lib\site-packages\storey\sources.py", line 747, in raise_error_or_return_termination_result
    self._raise_on_error(self._termination_q.get())
  File "C:\Python\test\.venv\lib\site-packages\storey\sources.py", line 736, in _raise_on_error
    raise self._ex
  File "C:\Python\test\.venv\lib\site-packages\storey\sources.py", line 719, in _async_loop_thread_main
    termination_result = await self._run_loop()
  File "C:\Python\test\.venv\lib\site-packages\storey\sources.py", line 835, in _run_loop
    return await self._do_downstream(_termination_obj)
  File "C:\Python\test\.venv\lib\site-packages\storey\flow.py", line 259, in _do_downstream
    self._termination_result = await self._outlets[0]._do(_termination_obj)
  File "C:\Python\test\.venv\lib\site-packages\storey\flow.py", line 1015, in _do
    await self._emit_all()
  File "C:\Python\test\.venv\lib\site-packages\storey\flow.py", line 1075, in _emit_all
    await self._emit_batch(key)
  File "C:\Python\test\.venv\lib\site-packages\storey\flow.py", line 1070, in _emit_batch
    await self._emit(batch_to_emit, batch_key, batch_time, self._batch_events[batch_key], last_event_time)
  File "C:\Python\test\.venv\lib\site-packages\storey\targets.py", line 650, in _emit
    df.to_parquet(path=file, index=bool(self._index_cols), version="2.4", **kwargs)
  File "C:\Python\test\.venv\lib\site-packages\pandas\util\_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "C:\Python\test\.venv\lib\site-packages\pandas\core\frame.py", line 2835, in to_parquet
    return to_parquet(
  File "C:\Python\test\.venv\lib\site-packages\pandas\io\parquet.py", line 420, in to_parquet
    impl.write(
  File "C:\Python\test\.venv\lib\site-packages\pandas\io\parquet.py", line 174, in write
    table = self.api.Table.from_pandas(df, **from_pandas_kwargs)
  File "pyarrow\table.pxi", line 3557, in pyarrow.lib.Table.from_pandas
  File "C:\Python\test\.venv\lib\site-packages\pyarrow\pandas_compat.py", line 611, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "C:\Python\test\.venv\lib\site-packages\pyarrow\pandas_compat.py", line 611, in <listcomp>
    arrays = [convert_column(c, f)
  File "C:\Python\test\.venv\lib\site-packages\pyarrow\pandas_compat.py", line 598, in convert_column
    raise e
  File "C:\Python\test\.venv\lib\site-packages\pyarrow\pandas_compat.py", line 592, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow\array.pxi", line 316, in pyarrow.lib.array
  File "pyarrow\array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow\error.pxi", line 123, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected bytes, got a 'datetime.date' object", 'Conversion failed for column party-establishment with type object')
```

### Expected Behavior

Without exception for ParquetSource

### Installation OS

Windows

### Installation Method

Docker

### Python Version

3.9.10

### MLRun Version

1.6.2

**Comment by george0st** [comment]
NOTE: It works correctly in case, that **infer_options=mlrun.data_types.data_types.InferOptions.Null** (not InferOptions.default())

**Comment by george0st** [comment]
Solved
