### ISSUE TITLE
[Installation]: Repeated CrashLoopBackOff cycle with MLRun-API-Chief pod until failure

### ISSUE THREAD

**Issue by bcorfman** [mlrun/mlrun#5955]
### Installation check

- [X] I have read the [installation guide](https://docs.mlrun.org/en/latest/install.html).

### Installation OS

Windows

### Installation Method

Kubernetes

### Kubernetes Cluster Type

K3s

### MLRun CE Version

0.6.2

### Issue Description

Going through the install of mlrun-ce on either the latest Docker Desktop (4.31.1) or Rancher Desktop (1.14.2) with Kubernetes results the mlrun-api-chief pod going through a repeated CrashLoopBackOff cycle until failure. All the other pods are up and running. System, pod and log details below.

```
bcorfman@vision:~/dev$ wsl.exe --version
WSL version: 2.2.4.0
Kernel version: 5.15.153.1-2
WSLg version: 1.0.61
MSRDC version: 1.2.5326
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.26091.1-240325-1447.ge-release
Windows version: 10.0.26120.961

bcorfman@vision:~$ kubectl -n mlrun get pods
NAME                                               READY   STATUS             RESTARTS        AGE
grafana-b448dd9d4-9wfqz                            3/3     Running            0               89m
metadata-envoy-deployment-5cdcb59886-jkkw8         1/1     Running            0               89m
metadata-grpc-deployment-b45564d7d-jw2h5           1/1     Running            3 (89m ago)     89m
metadata-writer-844659476c-l2lxp                   1/1     Running            0               89m
minio-0                                            1/1     Running            0               89m
minio-1                                            1/1     Running            0               89m
minio-2                                            1/1     Running            0               89m
minio-3                                            1/1     Running            0               89m
ml-pipeline-f98866669-8j7ws                        1/1     Running            4 (88m ago)     89m
ml-pipeline-persistenceagent-867f9455f-rrht6       1/1     Running            0               89m
ml-pipeline-scheduledworkflow-7fff4fbbfd-vft5x     1/1     Running            0               89m
ml-pipeline-ui-846cdf6d5-9zfj5                     1/1     Running            0               89m
ml-pipeline-viewer-crd-69c567884c-sdtbt            1/1     Running            0               89m
ml-pipeline-visualizationserver-5f68958dbf-7qv25   1/1     Running            0               89m
mlrun-api-chief-ff665c787-4tpzn                    0/1     CrashLoopBackOff   21 (117s ago)   89m
mlrun-db-5976b86cb6-rkj6p                          1/1     Running            0               89m
mlrun-jupyter-5c4f56d6b8-xnk4d                     1/1     Running            0               89m
mlrun-ui-79d857466-n428g                           1/1     Running            0               89m
monitoring-operator-64dd85bdf7-s54sw               1/1     Running            0               89m
mpi-operator-c58f6b78f-5nctj                       1/1     Running            0               89m
mysql-cc4ff9497-6kcj2                              1/1     Running            0               89m
node-exporter-5cw44                                1/1     Running            0               89m
nuclio-controller-ff5d666cd-qjmf4                  1/1     Running            0               89m
nuclio-dashboard-796cc85964-ngcd2                  1/1     Running            0               89m
prometheus-monitoring-prometheus-0                 2/2     Running            0               89m
spark-operator-6f75d6c67b-stq5t                    1/1     Running            0               89m
spark-operator-webhook-init-gqv8t                  0/1     Completed          0               90m
state-metrics-9498b9b44-bgp2n                      1/1     Running            0               89m
workflow-controller-5874fd4c9-b8pr4                1/1     Running            0               89m

bcorfman@vision:~$ kubectl -n mlrun logs mlrun-api-chief-ff665c787-4tpzn
> 2024-07-13 23:22:05,112 [info] Initializing DB data
> 2024-07-13 23:22:05,146 [info] No projects in DB, assuming latest data version: {'exc': ProgrammingError('(pymysql.err.ProgrammingError) (1146, "Table \'mlrun.data_versions\' doesn\'t exist")'), 'latest_data_version': 3}
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
> 2024-07-13 23:22:05,190 [info] No projects in DB, assuming latest data version: {'exc': ProgrammingError('(pymysql.err.ProgrammingError) (1146, "Table \'mlrun.data_versions\' doesn\'t exist")'), 'latest_data_version': 3}
> 2024-07-13 23:22:05,190 [info] Checking if migration is needed: {'is_migration_from_scratch': True, 'is_schema_migration_needed': True, 'is_data_migration_needed': False, 'is_database_migration_needed': False, 'is_backup_needed': False, 'is_migration_needed': False}
> 2024-07-13 23:22:05,190 [info] Creating initial data
> 2024-07-13 23:22:05,190 [info] Performing schema migration
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> c4af40b0bf61, init
> 2024-07-13 23:22:05,203 [warning] Migrations failed, changing API state: {'state': 'migrations_failed'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.9/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1050, "Table 'artifacts' already exists")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mlrun/mlrun/api/main.py", line 705, in <module>
    main()
  File "/mlrun/mlrun/api/main.py", line 680, in main
    init_data()
  File "/mlrun/mlrun/api/initial_data.py", line 94, in init_data
    _perform_schema_migrations(alembic_util)
  File "/mlrun/mlrun/api/initial_data.py", line 191, in _perform_schema_migrations
    alembic_util.init_alembic()
  File "/mlrun/mlrun/api/utils/db/alembic.py", line 38, in init_alembic
    alembic.command.upgrade(self._alembic_config, "head")
  File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 385, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mlrun/mlrun/api/migrations_mysql/env.py", line 96, in <module>
    run_migrations_online()
  File "/mlrun/mlrun/api/migrations_mysql/env.py", line 90, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.9/site-packages/alembic/runtime/environment.py", line 928, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.9/site-packages/alembic/runtime/migration.py", line 628, in run_migrations
    step.migration_fn(**kw)
  File "/mlrun/mlrun/api/migrations_mysql/versions/c4af40b0bf61_init.py", line 37, in upgrade
    op.create_table(
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/usr/local/lib/python3.9/site-packages/alembic/operations/ops.py", line 1277, in create_table
    return operations.invoke(op)
  File "/usr/local/lib/python3.9/site-packages/alembic/operations/base.py", line 395, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python3.9/site-packages/alembic/operations/toimpl.py", line 114, in create_table
    operations.impl.create_table(table)
  File "/usr/local/lib/python3.9/site-packages/alembic/ddl/impl.py", line 354, in create_table
    self._exec(schema.CreateTable(table))
  File "/usr/local/lib/python3.9/site-packages/alembic/ddl/impl.py", line 193, in _exec
    return conn.execute(  # type: ignore[call-overload]
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1477, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.9/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1050, "Table 'artifacts' already exists")
[SQL:
CREATE TABLE artifacts (
        id INTEGER NOT NULL AUTO_INCREMENT,
        `key` VARCHAR(255) COLLATE utf8_bin,
        project VARCHAR(255) COLLATE utf8_bin,
        uid VARCHAR(255) COLLATE utf8_bin,
        updated TIMESTAMP NULL,
        body MEDIUMBLOB,
        CONSTRAINT _artifacts_pk PRIMARY KEY (id),
        CONSTRAINT _artifacts_uc UNIQUE (uid, project, `key`)
)

]
(Background on this error at: https://sqlalche.me/e/14/e3q8)```

### Installation Logs

<details>

</details>


### Additional Information

_No response_

**Comment by bcorfman** [comment]
I followed the [Install MLRun on Kubernetes](https://docs.mlrun.org/en/stable/install/kubernetes.html) guide.

Some Slack interaction on the issue:
Brandon Corfman: I have reset several times and it always happens the same way.
`>kubectl describe pod mysql-<your-mysql-pod>`
`mysql:5.7`

**Comment by liranbg** [comment]
Hello @bcorfman,

Thank you for raising this issue. I have encountered this issue myself actually playing with running mlrun ce on top of "colima" (if you have mac OS - it is a great technology to play with). Then after redeploying I saw that mysql (upstream) has changed their patch version from 0.41 to 0.37 (probably yanked due to bugs).
After completely redeploy the error itself was gone, so I believe the root cause is somewhere between mysql patch versions that were yanked.

Can you please retry deploying mlrun ce (and ensure you have the "latest" mysql 8.0 image that is there on dockerhub) and let us know how it went?

**Comment by bcorfman** [comment]
I tried the MySQL 8.0 image. It went badly: Fewer of the pods came up this time, and the Helm Install timed out.
How do you guys test your Kubernetes install process? Do you have a continuous deployment process happening somewhere?

**Comment by mikenyaga** [comment]
>You can sort this error by deleting pvc's under mlrun namespace.
>But after that you will also get another error-  then the cycle repeats.
---------------------------- NEXT ERROR ------------------------------------
 2024-10-03 12:45:10,634 [info] Initializing DB data
> 2024-10-03 12:45:14,036 [info] No projects in DB, assuming latest data version: {'exc': ProgrammingError('(pymysql.err.ProgrammingError) (1146, "Table \'mlrun.data_versions\' doesn\'t exist")'), 'latest_data_version': 3}
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
> 2024-10-03 12:45:14,199 [info] No projects in DB, assuming latest data version: {'exc': ProgrammingError('(pymysql.err.ProgrammingError) (1146, "Table \'mlrun.data_versions\' doesn\'t exist")'), 'latest_data_version': 3}
> 2024-10-03 12:45:14,200 [info] Checking if migration is needed: {'is_migration_from_scratch': True, 'is_schema_migration_needed': True, 'is_data_migration_needed': False, 'is_database_migration_needed': False, 'is_backup_needed': False, 'is_migration_needed': False}
> 2024-10-03 12:45:14,200 [info] Creating initial data
> 2024-10-03 12:45:14,200 [info] Performing schema migration
INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> c4af40b0bf61, init
> 2024-10-03 12:45:14,397 [warning] Migrations failed, changing API state: {'state': 'migrations_failed'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.9/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (6125, "Failed to add the foreign key constraint. Missing unique key for constraint '_feature_sets_tags_obj_name_fk' in the referenced table 'feature_sets'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mlrun/mlrun/api/main.py", line 705, in <module>
    main()
  File "/mlrun/mlrun/api/main.py", line 680, in main
    init_data()
  File "/mlrun/mlrun/api/initial_data.py", line 94, in init_data
    _perform_schema_migrations(alembic_util)
  File "/mlrun/mlrun/api/initial_data.py", line 191, in _perform_schema_migrations
    alembic_util.init_alembic()
  File "/mlrun/mlrun/api/utils/db/alembic.py", line 38, in init_alembic
    alembic.command.upgrade(self._alembic_config, "head")
  File "/usr/local/lib/python3.9/site-packages/alembic/command.py", line 385, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.9/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mlrun/mlrun/api/migrations_mysql/env.py", line 96, in <module>
    run_migrations_online()
  File "/mlrun/mlrun/api/migrations_mysql/env.py", line 90, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.9/site-packages/alembic/runtime/environment.py", line 928, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.9/site-packages/alembic/runtime/migration.py", line 628, in run_migrations
    step.migration_fn(**kw)
  File "/mlrun/mlrun/api/migrations_mysql/versions/c4af40b0bf61_init.py", line 363, in upgrade
    op.create_table(
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/usr/local/lib/python3.9/site-packages/alembic/operations/ops.py", line 1277, in create_table
    return operations.invoke(op)
  File "/usr/local/lib/python3.9/site-packages/alembic/operations/base.py", line 395, in invoke
    return fn(self, operation)
  File "/usr/local/lib/python3.9/site-packages/alembic/operations/toimpl.py", line 114, in create_table
    operations.impl.create_table(table)
  File "/usr/local/lib/python3.9/site-packages/alembic/ddl/impl.py", line 354, in create_table
    self._exec(schema.CreateTable(table))
  File "/usr/local/lib/python3.9/site-packages/alembic/ddl/impl.py", line 193, in _exec
    return conn.execute(  # type: ignore[call-overload]
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1477, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.9/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.9/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.9/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.9/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.9/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (6125, "Failed to add the foreign key constraint. Missing unique key for constraint '_feature_sets_tags_obj_name_fk' in the referenced table 'feature_sets'")
[SQL:
CREATE TABLE feature_sets_tags (
	id INTEGER NOT NULL AUTO_INCREMENT,
	project VARCHAR(255) COLLATE utf8_bin,
	name VARCHAR(255) COLLATE utf8_bin,
	obj_id INTEGER,
	obj_name VARCHAR(255) COLLATE utf8_bin,
	CONSTRAINT _feature_sets_tags_pk PRIMARY KEY (id),
	CONSTRAINT _feature_sets_tags_obj_id_fk FOREIGN KEY(obj_id) REFERENCES feature_sets (id),
	CONSTRAINT _feature_sets_tags_obj_name_fk FOREIGN KEY(obj_name) REFERENCES feature_sets (name),
	CONSTRAINT _feature_sets_tags_uc UNIQUE (project, name, obj_name)
)

]

**Comment by AICBIC** [comment]
I'm the same, how can we solve this problem？

**Comment by mikenyaga** [comment]
Use mlrun-ce-0.6.4-rc16

**Comment by alonmr** [comment]
This was fixed apparently, I believe in 0.6.3-rc19.
