### ISSUE TITLE
mlrun-api pod crashing on kubernetes cluster (v0.5.x-latest).

### ISSUE THREAD

**Issue by Vin-itall** [mlrun/mlrun#716]
I am trying to deploy mlrun on a kubernetes cluster in the kubeflow namespace with kfp installed on it. 
Using this documentation (v0.5.x-latest) (https://mlrun.readthedocs.io/en/release-v0.5.x-latest/install.html) as End-to-end Pipeline Tutorial isn't working on the latest release (https://mlrun.readthedocs.io/en/v0.6.0/install.html). 

The mlrun -api pod swiches from running to error to crashloopback to running again.

```
kubectl logs  mlrun-api-7745fb596-mqnrz -n kubeflow
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 170, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1032, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.7/http/client.py", line 972, in send
    self.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 182, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f80485dc9d0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 796, in urlopen
    **response_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='mlrun-api', port=8080): Max retries exceeded with url: /api/healthz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f80485dc9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mlrun/mlrun/db/httpdb.py", line 159, in api_call
    method, url, timeout=timeout, verify=False, **kw
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='mlrun-api', port=8080): Max retries exceeded with url: /api/healthz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f80485dc9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/mlrun/mlrun/__init__.py", line 22, in <module>
    from .config import config as mlconf
  File "/mlrun/mlrun/config.py", line 370, in <module>
    _populate()
  File "/mlrun/mlrun/config.py", line 259, in _populate
    _do_populate()
  File "/mlrun/mlrun/config.py", line 281, in _do_populate
    config.update(data)
  File "/mlrun/mlrun/config.py", line 187, in update
    setattr(self, key, value)
  File "/mlrun/mlrun/config.py", line 170, in __setattr__
    super().__setattr__(attr, value)
  File "/mlrun/mlrun/config.py", line 243, in dbpath
    mlrun.db.get_run_db(value)
  File "/mlrun/mlrun/db/__init__.py", line 87, in get_run_db
    _run_db.connect(secrets=secrets)
  File "/mlrun/mlrun/db/httpdb.py", line 198, in connect
    resp = self.api_call("GET", "healthz", timeout=5)
  File "/mlrun/mlrun/db/httpdb.py", line 163, in api_call
    raise RunDBError(error) from err
mlrun.db.base.RunDBError: GET http://mlrun-api:8080/api/healthz, error: HTTPConnectionPool(host='mlrun-api', port=8080): Max retries exceeded with url: /api/healthz (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f80485dc9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

Please help me out with this. Thanks in advance. Let me know if you need more details.

**Comment by Vin-itall** [comment]
@omesser can you help me out with this?
